language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  - chrome: stable
before_install: 
  - npm i -g codecov
install:
  - yarn
script:
  - npm run lint
  - npm run test_node
  - npm run test_headless
  - codecov
cache:
  yarn: true
  directories:
    - node_modules
after_success:
  - export CODECOV_TOKEN="0b680ee0-cea5-45a1-a924-bccbf92fbbe5"
  - bash <(curl -s https://codecov.io/bash) -s coverage/